import { Inter } from "next/font/google";
import "./globals.css";
import MuiConfig from "@/configaration/MUI.config";
import GlobalContextProvider from "@/context/GlobalContext";
import AuthProvider from "@/context/AuthContext";
import { Toaster } from "react-hot-toast";
import PrivateRoute from "@/Routes/PrivateRoute";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <GlobalContextProvider>
          <AuthProvider>
            <MuiConfig>
              <PrivateRoute>
                {children}
              </PrivateRoute>
              <Toaster />
            </MuiConfig>
          </AuthProvider>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
